/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.iot.sensors;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LocationRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocationRecord\",\"namespace\":\"org.apache.iot.sensors\",\"fields\":[{\"name\":\"longitude\",\"type\":\"double\"},{\"name\":\"latitude\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public double longitude;
  @Deprecated public double latitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public LocationRecord() {}

  /**
   * All-args constructor.
   */
  public LocationRecord(java.lang.Double longitude, java.lang.Double latitude) {
    this.longitude = longitude;
    this.latitude = latitude;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return longitude;
    case 1: return latitude;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: longitude = (java.lang.Double)value$; break;
    case 1: latitude = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'longitude' field.
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.Double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.Double value) {
    this.latitude = value;
  }

  /** Creates a new LocationRecord RecordBuilder */
  public static org.apache.iot.sensors.LocationRecord.Builder newBuilder() {
    return new org.apache.iot.sensors.LocationRecord.Builder();
  }
  
  /** Creates a new LocationRecord RecordBuilder by copying an existing Builder */
  public static org.apache.iot.sensors.LocationRecord.Builder newBuilder(org.apache.iot.sensors.LocationRecord.Builder other) {
    return new org.apache.iot.sensors.LocationRecord.Builder(other);
  }
  
  /** Creates a new LocationRecord RecordBuilder by copying an existing LocationRecord instance */
  public static org.apache.iot.sensors.LocationRecord.Builder newBuilder(org.apache.iot.sensors.LocationRecord other) {
    return new org.apache.iot.sensors.LocationRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for LocationRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocationRecord>
    implements org.apache.avro.data.RecordBuilder<LocationRecord> {

    private double longitude;
    private double latitude;

    /** Creates a new Builder */
    private Builder() {
      super(org.apache.iot.sensors.LocationRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.apache.iot.sensors.LocationRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.longitude)) {
        this.longitude = data().deepCopy(fields()[0].schema(), other.longitude);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing LocationRecord instance */
    private Builder(org.apache.iot.sensors.LocationRecord other) {
            super(org.apache.iot.sensors.LocationRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.longitude)) {
        this.longitude = data().deepCopy(fields()[0].schema(), other.longitude);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'longitude' field */
    public java.lang.Double getLongitude() {
      return longitude;
    }
    
    /** Sets the value of the 'longitude' field */
    public org.apache.iot.sensors.LocationRecord.Builder setLongitude(double value) {
      validate(fields()[0], value);
      this.longitude = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'longitude' field has been set */
    public boolean hasLongitude() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'longitude' field */
    public org.apache.iot.sensors.LocationRecord.Builder clearLongitude() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'latitude' field */
    public java.lang.Double getLatitude() {
      return latitude;
    }
    
    /** Sets the value of the 'latitude' field */
    public org.apache.iot.sensors.LocationRecord.Builder setLatitude(double value) {
      validate(fields()[1], value);
      this.latitude = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'latitude' field has been set */
    public boolean hasLatitude() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'latitude' field */
    public org.apache.iot.sensors.LocationRecord.Builder clearLatitude() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public LocationRecord build() {
      try {
        LocationRecord record = new LocationRecord();
        record.longitude = fieldSetFlags()[0] ? this.longitude : (java.lang.Double) defaultValue(fields()[0]);
        record.latitude = fieldSetFlags()[1] ? this.latitude : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
